### ISSUE TITLE
Readme is incorrect

### ISSUE THREAD

**Issue by dnwillia-work** [igrr/astyle_py#3]
It says to use v1.0.0 but you only have v0.9.0.

**Comment by igrr** [comment]
That was just an example that there should be a tag, not `main` or `master`. Sorry for not being clear. I'll update the Readme.

**Comment by dnwillia-work** [comment]
Yup. I had figured it out but thought I'd let you know.  You might just keep the doc at the latest release.

**Comment by igrr** [comment]
v1.0.0 is released, so the readme file is finally in sync with the version.
