### ISSUE TITLE
Use Astyle exe and not wasm?

### ISSUE THREAD

**Issue by dnwillia-work** [igrr/astyle_py#4]
Is it possible to make your plug-in work with a raw AStyle executable?  I got it running but I can't use the WASM because we use a custom modified version of AStyle.

**Comment by igrr** [comment]
It's possible, but the implementation would be totally different. 

This python wrapper calls the internal Astyle API to format the input, whereas if we were to call the .exe, the said .exe would also handle the arguments and options parsing.

What you can do is: fork the project, rebuild the WASM binary from your fork of Astyle. Then either push the resulting package to PyPI, or install it directly from Git.

**Comment by dnwillia-work** [comment]
Ok sounds good and makes sense.  Let me look at that.

**Comment by Freed-Wu** [comment]
@dnwillia-work If you want to use native binary program not wasm of astyle in python or pre-commit hooks, you can see [this project](https://github.com/Freed-Wu/astyle-wheel/).
